name: Build Orbital

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Github User Configuration
        run: |
             git config --global user.email "pragyan.krish3@gmail.com"
             git config --global user.name "Pratech1015"
      - name: Apply patches
        run: ./gradlew applyPatches

      - name: Build paperclip jar
        run: ./gradlew createMojmapPaperclipJar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: orbital-server
          path: build/libs/*.jar

      - name: Get Minecraft version
        id: mcver
        run: |
          VERSION=$(grep mcVersion gradle.properties | cut -d '=' -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Determine release number
        id: version
        run: |
          VERSION="${{ steps.mcver.outputs.version }}"
          COUNT=$(gh release list --limit 100 | grep "Orbital $VERSION" | wc -l)

          if [ "$COUNT" -eq 0 ]; then
            NAME="Orbital $VERSION"
            TAG="orbital-$VERSION"
          else
            NUM=$((COUNT+1))
            NAME="Orbital $VERSION #$NUM"
            TAG="orbital-$VERSION-$NUM"
          fi

          echo "name=$NAME" >> $GITHUB_OUTPUT
          echo "tag=$TAG" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          name: ${{ steps.version.outputs.name }}
          files: paper-server/build/libs/*.jar
